version: "3.7"

services:
    mysql:
        container_name: products_mysql
        tty: true
        image: mysql:8
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE:-products}
            MYSQL_USER: ${MYSQL_USER:-products_user}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-products_password}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-products_root_password}
        volumes:
            - ./docker/data/mysql:/var/lib/mysql
        ports:
            - 7306:3306
        depends_on:
            - web
        networks:
            - products-net
    mysql_test:
        container_name: products_mysql_test
        tty: true
        image: mysql:8
        environment:
            MYSQL_DATABASE: products_test
            MYSQL_USER: products_user_test
            MYSQL_PASSWORD: products_password_test
            MYSQL_ROOT_PASSWORD: products_root_password_test
        volumes:
            - ./docker/data/mysql_test:/var/lib/mysql
        ports:
            - 7307:3306
        depends_on:
          - web
        networks:
          - products-net
    web:
        container_name: products_web
        tty: true
        build:
            dockerfile: ./docker/php8.2-apache/Dockerfile
            context: .
            args:
                COMPOSER_DEV: ${COMPOSER_DEV:-true}
                XDEBUG_FILE_LINK_FORMAT: ${XDEBUG_FILE_LINK_FORMAT:-}
        ports:
            - 8070:80
        volumes:
            - .:/var/www/html
        environment:
            XDEBUG_MODE: ${XDEBUG_MODE:-off}
            XDEBUG_CONFIG: ${XDEBUG_CONFIG:-client_host=host.docker.internal client_port=9003 log=/temp/xdebug.log discover_client_host=true  idekey=phpstorm}
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - products-net

networks:
    products-net:
        name: products-net
        driver: bridge

